

export const movies = [
    {
      "id": "1930",
      "plot": "Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.",
      "popularity": 285.126,
      "release_date": "2012-06-23",
      "adult": false,
      "trailer": "https://www.youtube.com/embed/WLxul0Vzuhk",
      "vote_average": 6.7,
      "genre": "Action",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//sLWUtbrpiLp23a0XDSiUiltdFPJ.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//fSbqPbqXa7ePo8bcnZYN9AHv6zA.jpg",
      "title": "The Amazing Spider-Man",
      "original_language": "en"
    },
    {
      "id": "19995",
      "vote_average": 7.5,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//jlQJDD0L5ZojjlS0KYnApdO0n19.jpg",
      "title": "Avatar",
      "popularity": 299.322,
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
      "trailer": "https://www.youtube.com/embed/5PSNL1qE6VY",
      "plot": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
      "adult": false,
      "release_date": "2009-12-10",
      "genre": "Action"
    },
    {
      "id": "24428",
      "genre": "Science Fiction",
      "title": "The Avengers",
      "original_language": "en",
      "adult": false,
      "popularity": 256.121,
      "vote_average": 7.7,
      "poster_path": "https://image.tmdb.org/t/p/w500//RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//nNmJRkg8wWnRmzQDe2FwKbPIsJV.jpg",
      "trailer": "https://www.youtube.com/embed/hIR8Ar-Z4hw",
      "plot": "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
      "release_date": "2012-04-25"
    },
    {
      "id": "284052",
      "vote_average": 7.4,
      "poster_path": "https://image.tmdb.org/t/p/w500//uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
      "trailer": "https://www.youtube.com/embed/HSzx-zryEgM",
      "release_date": "2016-10-25",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//aL53oMdZKZRJRH8txH07DLuleF9.jpg",
      "original_language": "en",
      "genre": "Action",
      "plot": "After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
      "popularity": 298.696,
      "title": "Doctor Strange",
      "adult": false
    },
    {
      "id": "299534",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
      "adult": false,
      "popularity": 285.781,
      "plot": "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
      "genre": "Adventure",
      "title": "Avengers: Endgame",
      "vote_average": 8.3,
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      "release_date": "2019-04-24",
      "trailer": "https://www.youtube.com/embed/AMSITikqKiM"
    },
    {
      "id": "299536",
      "adult": false,
      "popularity": 399.935,
      "release_date": "2018-04-25",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
      "plot": "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
      "poster_path": "https://image.tmdb.org/t/p/w500//7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      "title": "Avengers: Infinity War",
      "genre": "Adventure",
      "trailer": "https://www.youtube.com/embed/QwievZ1Tx-8",
      "vote_average": 8.3,
      "original_language": "en"
    },
    {
      "id": "335787",
      "trailer": "https://www.youtube.com/embed/l-LD16Yzi2c",
      "original_language": "en",
      "popularity": 677.833,
      "plot": "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
      "title": "Uncharted",
      "adult": false,
      "vote_average": 7.1,
      "poster_path": "https://image.tmdb.org/t/p/w500//sqLowacltbZLoCa4KYye64RvvdQ.jpg",
      "release_date": "2022-02-10",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//cTTggc927lEPCMsWUsdugSj6wAY.jpg",
      "genre": "Action"
    },
    {
      "id": "337404",
      "poster_path": "https://image.tmdb.org/t/p/w500//wToO8opxkGwKgSfJ1JK8tGvkG6U.jpg",
      "genre": "Comedy",
      "vote_average": 8.2,
      "original_language": "en",
      "plot": "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
      "release_date": "2021-05-26",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//LTOZB3N1kYA2Xu1lW114HFA1o8.jpg",
      "trailer": "https://www.youtube.com/embed/jpZrVxvG3mk",
      "title": "Cruella",
      "popularity": 375.689
    },
    {
      "id": "338953",
      "trailer": "https://www.youtube.com/embed/DaM_wL1ZOM4",
      "popularity": 370.796,
      "adult": false,
      "original_language": "en",
      "title": "Fantastic Beasts: The Secrets of Dumbledore",
      "release_date": "2022-04-07",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//mZ3dl55cY8xtbzX06MOh31pV84Y.jpg",
      "genre": "Fantasy",
      "vote_average": 5.7,
      "plot": "In an effort to thwart Grindelwald's plans of raising pure-blood wizards to rule over all non-magical beings, Albus Dumbledore enlists his former student Newt Scamander, who agrees to help, though he's unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
      "poster_path": "https://image.tmdb.org/t/p/w500//3shu40ezblcqGZV4YbznZ0NHTHF.jpg"
    },
    {
      "id": "370172",
      "vote_average": 7.5,
      "release_date": "2021-09-29",
      "title": "No Time to Die",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//r2GAjd4rNOHJh6i6Y0FntmYuPQW.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
      "popularity": 363.277,
      "original_language": "en",
      "adult": false,
      "genre": "Adventure",
      "trailer": "https://www.youtube.com/embed/N_gD9-Oa0fg",
      "plot": "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology."
    },
    {
      "id": "379686",
      "popularity": 302.444,
      "release_date": "2021-07-08",
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//8s4h9friP6Ci3adRGahHARVd76E.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg",
      "genre": "Family",
      "trailer": "https://www.youtube.com/embed/foNoodDwXS8",
      "plot": "When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.",
      "title": "Space Jam: A New Legacy",
      "adult": false,
      "vote_average": 7.1
    },
    {
      "id": "385128",
      "vote_average": 7.3,
      "release_date": "2021-05-19",
      "adult": false,
      "title": "F9",
      "poster_path": "https://image.tmdb.org/t/p/w500//bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
      "plot": "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
      "trailer": "https://www.youtube.com/embed/5eblKqTZ-0Q",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//fWjcUTKOKsAPK4VUAzEQW4kN4K6.jpg",
      "original_language": "en",
      "genre": "Action",
      "popularity": 362.191
    },
    {
      "id": "399566",
      "release_date": "2021-03-24",
      "plot": "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
      "original_language": "en",
      "genre": "Action",
      "title": "Godzilla vs. Kong",
      "trailer": "https://www.youtube.com/embed/odM92ap8_c0",
      "vote_average": 7.8,
      "popularity": 277.163,
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg"
    },
    {
      "id": "406759",
      "poster_path": "https://image.tmdb.org/t/p/w500//odVv1sqVs0KxBXiA8bhIBlPgalx.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//x747ZvF0CcYYTTpPRCoUrxA2cYy.jpg",
      "release_date": "2022-02-03",
      "plot": "A mysterious force knocks the moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.",
      "title": "Moonfall",
      "vote_average": 6.4,
      "popularity": 4501.778,
      "trailer": "https://www.youtube.com/embed/ivIwdQBlS10",
      "adult": false,
      "original_language": "en",
      "genre": "Action"
    },
    {
      "id": "414906",
      "poster_path": "https://image.tmdb.org/t/p/w500//74xTEgt7R36Fpooo50r9T25onhq.jpg",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//5P8SmMzSNYikXpxil6BYzJ16611.jpg",
      "vote_average": 7.9,
      "plot": "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
      "trailer": "https://www.youtube.com/embed/u34gHaRiBIU",
      "popularity": 1930.728,
      "original_language": "en",
      "title": "The Batman",
      "genre": "Crime",
      "release_date": "2022-03-01"
    },
    {
      "id": "423108",
      "popularity": 266.161,
      "poster_path": "https://image.tmdb.org/t/p/w500//xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg",
      "release_date": "2021-05-25",
      "original_language": "en",
      "trailer": "https://www.youtube.com/embed/tLFnRAzcaEc",
      "plot": "Paranormal investigators Ed and Lorraine Warren encounter what would become one of the most sensational cases from their files. The fight for the soul of a young boy takes them beyond anything they'd ever seen before, to mark the first time in U.S. history that a murder suspect would claim demonic possession as a defense.",
      "vote_average": 7.7,
      "genre": "Horror",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//qi6Edc1OPcyENecGtz8TF0DUr9e.jpg",
      "adult": false,
      "title": "The Conjuring: The Devil Made Me Do It"
    },
    {
      "id": "425909",
      "release_date": "2021-11-11",
      "popularity": 671.835,
      "adult": false,
      "trailer": "https://www.youtube.com/embed/lnKmAVLC3jU",
      "genre": "Fantasy",
      "plot": "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
      "title": "Ghostbusters: Afterlife",
      "vote_average": 7.7,
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//sg4xJaufDiQl7caFEskBtQXfD4x.jpg"
    },
    {
      "id": "436969",
      "poster_path": "https://image.tmdb.org/t/p/w500//kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg",
      "plot": "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
      "adult": false,
      "title": "The Suicide Squad",
      "popularity": 390.067,
      "vote_average": 7.7,
      "genre": "Action",
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg",
      "release_date": "2021-07-28",
      "trailer": "https://www.youtube.com/embed/eg5ciqQzmK0"
    },
    {
      "id": "438631",
      "vote_average": 7.9,
      "title": "Dune",
      "popularity": 467.4,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
      "plot": "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
      "trailer": "https://www.youtube.com/embed/w0HgHet0sxg",
      "genre": "Science Fiction",
      "adult": false,
      "release_date": "2021-09-15"
    },
    {
      "id": "438695",
      "vote_average": 8.1,
      "trailer": "https://www.youtube.com/embed/EPZu5MA2uqI",
      "genre": "Animation",
      "popularity": 860.012,
      "release_date": "2021-12-01",
      "adult": false,
      "poster_path": "https://image.tmdb.org/t/p/w500//aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
      "original_language": "en",
      "title": "Sing 2",
      "plot": "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg"
    },
    {
      "id": "451048",
      "poster_path": "https://image.tmdb.org/t/p/w500//9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
      "adult": false,
      "title": "Jungle Cruise",
      "genre": "Action",
      "plot": "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.",
      "vote_average": 7.6,
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//7WJjFviFBffEJvkAms4uWwbcVUk.jpg",
      "popularity": 325.001,
      "release_date": "2021-07-28",
      "trailer": "https://www.youtube.com/embed/hJZ82pwwJqA"
    },
    {
      "id": "454626",
      "title": "Sonic the Hedgehog",
      "plot": "Powered with incredible speed, Sonic The Hedgehog embraces his new home on Earth. That is, until Sonic sparks the attention of super-uncool evil genius Dr. Robotnik. Now it’s super-villain vs. super-sonic in an all-out race across the globe to stop Robotnik from using Sonic’s unique power for world domination.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg",
      "release_date": "2020-02-12",
      "genre": "Action",
      "trailer": "https://www.youtube.com/embed/szby7ZHLnkA",
      "vote_average": 7.4,
      "original_language": "en",
      "adult": false,
      "popularity": 997.472
    },
    {
      "id": "459151",
      "trailer": "https://www.youtube.com/embed/-rF2j6K5FoM",
      "plot": "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
      "genre": "Animation",
      "vote_average": 7.6,
      "original_language": "en",
      "adult": false,
      "popularity": 691.875,
      "poster_path": "https://image.tmdb.org/t/p/w500//kv2Qk9MKFFQo4WQPaYta599HkJP.jpg",
      "title": "The Boss Baby: Family Business",
      "release_date": "2021-07-01",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//pxOiKwRvNp3zFOiuwpYpzlbmEgC.jpg"
    },
    {
      "id": "460458",
      "release_date": "2021-11-24",
      "title": "Resident Evil: Welcome to Raccoon City",
      "vote_average": 6.2,
      "trailer": "https://www.youtube.com/embed/IQqqAWMIIAQ",
      "poster_path": "https://image.tmdb.org/t/p/w500//7uRbWOXxpWDMtnsd2PF3clu65jc.jpg",
      "adult": false,
      "genre": "Horror",
      "popularity": 725.99,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//o76ZDm8PS9791XiuieNB93UZcRV.jpg",
      "plot": "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
      "original_language": "en"
    },
    {
      "id": "460465",
      "adult": false,
      "popularity": 431.884,
      "plot": "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
      "vote_average": 7.2,
      "original_language": "en",
      "trailer": "https://www.youtube.com/embed/QJHY4ggYCk4",
      "title": "Mortal Kombat",
      "genre": "Action",
      "release_date": "2021-04-07",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg"
    },
    {
      "id": "476669",
      "genre": "Action",
      "title": "The King's Man",
      "popularity": 1075.41,
      "vote_average": 7,
      "release_date": "2021-12-22",
      "original_language": "en",
      "adult": false,
      "plot": "As a collection of history's worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them.",
      "poster_path": "https://image.tmdb.org/t/p/w500//aq4Pwv5Xeuvj6HZKtxyd23e6bE9.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//4OTYefcAlaShn6TGVK33UxLW9R7.jpg",
      "trailer": "https://www.youtube.com/embed/_0vKejp3rvA"
    },
    {
      "id": "482321",
      "popularity": 506.798,
      "title": "Ron's Gone Wrong",
      "poster_path": "https://image.tmdb.org/t/p/w500//7M0uwPgwvPONdFG0jk8TPK09xJU.jpg",
      "trailer": "https://www.youtube.com/embed/8I8nMtzN05s",
      "genre": "Animation",
      "plot": "In a world where walking, talking, digitally connected bots have become children's best friends, an 11-year-old finds that his robot buddy doesn't quite work the same as the others do.",
      "vote_average": 8.1,
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//sdL37sfUBth7mdkAolI83bXAl7L.jpg",
      "release_date": "2021-10-15",
      "adult": false
    },
    {
      "id": "482373",
      "genre": "Thriller",
      "original_language": "en",
      "title": "Don't Breathe 2",
      "vote_average": 7.4,
      "poster_path": "https://image.tmdb.org/t/p/w500//r7HEBkkRN93d3eFBZgPJfRaob5p.jpg",
      "release_date": "2021-08-12",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//pUc51UUQb1lMLVVkDCaZVsCo37U.jpg",
      "plot": "The Blind Man has been hiding out for several years in an isolated cabin and has taken in and raised a young girl orphaned from a devastating house fire. Their quiet life together is shattered when a group of criminals kidnap the girl, forcing the Blind Man to leave his safe haven to save her.",
      "popularity": 246.964,
      "adult": false,
      "trailer": "https://www.youtube.com/embed/dCDLPlZAoeY"
    },
    {
      "id": "497698",
      "popularity": 329.894,
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
      "original_language": "en",
      "genre": "Action",
      "title": "Black Widow",
      "poster_path": "https://image.tmdb.org/t/p/w500//qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
      "plot": "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
      "release_date": "2021-07-07",
      "trailer": "https://www.youtube.com/embed/Fp9pNPdNwjI",
      "vote_average": 7.5
    },
    {
      "id": "505026",
      "poster_path": "https://image.tmdb.org/t/p/w500//kVr5zIAFSPRQ57Y1zE7KzmhzdMQ.jpg",
      "original_language": "en",
      "title": "Death on the Nile",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//lRbDyjI7HEaXxflFQbYpqHRGFBJ.jpg",
      "release_date": "2022-02-09",
      "plot": "Belgian sleuth Hercule Poirot boards a glamorous river steamer with enough champagne to fill the Nile. But his Egyptian vacation turns into a thrilling search for a murderer when a picture-perfect couple’s idyllic honeymoon is tragically cut short.",
      "genre": "Crime",
      "popularity": 1231.988,
      "trailer": "https://www.youtube.com/embed/dZRqB0JLizw",
      "vote_average": 6.6
    },
    {
      "id": "508943",
      "trailer": "https://www.youtube.com/embed/mYfJxlgR2jw",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//zdT9pVcXEKo2wpQb4HDPRWMQXvp.jpg",
      "adult": false,
      "title": "Luca",
      "original_language": "en",
      "release_date": "2021-06-17",
      "vote_average": 8,
      "poster_path": "https://image.tmdb.org/t/p/w500//jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
      "plot": "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
      "popularity": 415.508,
      "genre": "Animation"
    },
    {
      "id": "508947",
      "release_date": "2022-03-01",
      "genre": "Animation",
      "poster_path": "https://image.tmdb.org/t/p/w500//qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
      "title": "Turning Red",
      "plot": "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
      "popularity": 5329.202,
      "trailer": "https://www.youtube.com/embed/XdKzUbAiswE",
      "vote_average": 7.5,
      "original_language": "en",
      "adult": false
    },
    {
      "id": "511809",
      "title": "West Side Story",
      "popularity": 282.709,
      "plot": "Two youngsters from rival New York City gangs fall in love, but tensions between their respective friends build toward tragedy.",
      "original_language": "en",
      "genre": "Drama",
      "trailer": "https://www.youtube.com/embed/A5GJLwWiYSg",
      "release_date": "2021-12-08",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//tHnHTp50qDx7br1i9ulh74MUW0A.jpg",
      "vote_average": 7.2,
      "poster_path": "https://image.tmdb.org/t/p/w500//yfz3IUoYYSY32tkb97HlUBGFsnh.jpg"
    },
    {
      "id": "512195",
      "vote_average": 6.8,
      "adult": false,
      "popularity": 1664.77,
      "plot": "An Interpol-issued Red Notice is a global alert to hunt and capture the world's most wanted. But when a daring heist brings together the FBI's top profiler and two rival criminals, there's no telling what will happen.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//dK12GIdhGP6NPGFssK2Fh265jyr.jpg",
      "original_language": "en",
      "release_date": "2021-11-04",
      "title": "Red Notice",
      "genre": "Action",
      "poster_path": "https://image.tmdb.org/t/p/w500//lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
      "trailer": "https://www.youtube.com/embed/Pj0wz7zu3Ms"
    },
    {
      "id": "516329",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//9fzNf2QcsHVvdx5g5QUOgAWpADw.jpg",
      "adult": false,
      "genre": "Drama",
      "poster_path": "https://image.tmdb.org/t/p/w500//cMch3tiexw3FdOEeZxMWVel61Xg.jpg",
      "popularity": 271.919,
      "title": "Antlers",
      "plot": "A small-town Oregon teacher and her brother, the local sheriff, discover a young student is harbouring a dangerous secret that could have frightening consequences.",
      "trailer": "https://www.youtube.com/embed/2aiYxwVuZ1o",
      "original_language": "en",
      "release_date": "2021-10-28",
      "vote_average": 6.4
    },
    {
      "id": "522016",
      "popularity": 638.722,
      "release_date": "2022-01-05",
      "original_language": "en",
      "vote_average": 6,
      "plot": "A group of top female agents from American, British, Chinese, Columbian and German  government agencies are drawn together to try and stop an organization from acquiring a deadly weapon to send the world into chaos.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//8pgKccb5PfE1kWB9qqiXJem83VC.jpg",
      "title": "The 355",
      "trailer": "https://www.youtube.com/embed/SV0s2S9reT0",
      "adult": false,
      "genre": "Action",
      "poster_path": "https://image.tmdb.org/t/p/w500//zxizwEPE8jhpbMgrFbwCztgvh2m.jpg"
    },
    {
      "id": "522402",
      "original_language": "en",
      "trailer": "https://www.youtube.com/embed/-0bYWnP3jH4",
      "title": "Finch",
      "popularity": 339.288,
      "adult": false,
      "release_date": "2021-11-04",
      "plot": "On a post-apocalyptic Earth, a robot, built to protect the life of his dying creator's beloved dog, learns about life, love, friendship, and what it means to be human.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//oE6bhqqVFyIECtBzqIuvh6JdaB5.jpg",
      "genre": "Science Fiction",
      "vote_average": 8.1,
      "poster_path": "https://image.tmdb.org/t/p/w500//jKuDyqx7jrjiR9cDzB5pxzhJAdv.jpg"
    },
    {
      "id": "523936",
      "vote_average": 6,
      "release_date": "2021-05-26",
      "title": "Meander",
      "original_language": "fr",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//qOnLuCJDFhRzbWzhpA4aoK75vfY.jpg",
      "genre": "Horror",
      "plot": "After getting a car ride from an unknown man, Lisa wakes up in a tube. On her arm is strapped a bracelet with a countdown. She quickly understands that every 8 minutes, fire burns an occupied section. She has no choice but to crawl into safe sections to survive. To know why she’s there and how to get out, Lisa will have to face the memories of her dead daughter…",
      "adult": false,
      "popularity": 240.534,
      "poster_path": "https://image.tmdb.org/t/p/w500//2OTIAx8AmwGCaXmq5ohQCyPUjdC.jpg",
      "trailer": "https://www.youtube.com/embed/u1Q5jWpRCL4"
    },
    {
      "id": "524434",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//c6H7Z4u73ir3cIoCteuhJh7UCAR.jpg",
      "trailer": "https://www.youtube.com/embed/x_me3xsvDgk",
      "adult": false,
      "vote_average": 7.2,
      "original_language": "en",
      "popularity": 1099.605,
      "genre": "Science Fiction",
      "plot": "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.",
      "poster_path": "https://image.tmdb.org/t/p/w500//bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg",
      "release_date": "2021-11-03",
      "title": "Eternals"
    },
    {
      "id": "526896",
      "trailer": "https://www.youtube.com/embed/SQK-QxxtE8Y",
      "adult": false,
      "title": "Morbius",
      "poster_path": "https://image.tmdb.org/t/p/w500//6nhwr1LCozBiIN47b8oBEomOADm.jpg",
      "original_language": "en",
      "plot": "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//tj4lzGgHrfjnjVqAKkLIjFqPSyO.jpg",
      "release_date": "2022-03-30",
      "popularity": 1742.669,
      "genre": "Action",
      "vote_average": 5.7
    },
    {
      "id": "529203",
      "title": "The Croods: A New Age",
      "plot": "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
      "release_date": "2020-11-25",
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//fmIp40ev4VGquK2bMo52PQgaV2d.jpg",
      "popularity": 320.513,
      "adult": false,
      "genre": "Animation",
      "vote_average": 7.6,
      "trailer": "https://www.youtube.com/embed/hy4vAqF9Ko0",
      "poster_path": "https://image.tmdb.org/t/p/w500//tbVZ3Sq88dZaCANlUcewQuHQOaE.jpg"
    },
    {
      "id": "550988",
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
      "vote_average": 7.7,
      "popularity": 424.1,
      "genre": "Comedy",
      "poster_path": "https://image.tmdb.org/t/p/w500//xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",
      "title": "Free Guy",
      "plot": "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
      "trailer": "https://www.youtube.com/embed/cttnRmcr_ME",
      "adult": false,
      "release_date": "2021-08-11"
    },
    {
      "id": "566525",
      "plot": "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
      "popularity": 758.312,
      "original_language": "en",
      "release_date": "2021-09-01",
      "genre": "Action",
      "poster_path": "https://image.tmdb.org/t/p/w500//1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
      "vote_average": 7.7,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
      "title": "Shang-Chi and the Legend of the Ten Rings",
      "adult": false,
      "trailer": "https://www.youtube.com/embed/8YjFbMbfXaQ"
    },
    {
      "id": "568124",
      "poster_path": "https://image.tmdb.org/t/p/w500//4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
      "title": "Encanto",
      "trailer": "https://www.youtube.com/embed/bjMFebB2Coo",
      "genre": "Animation",
      "popularity": 1962.34,
      "vote_average": 7.7,
      "release_date": "2021-11-24",
      "plot": "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
      "original_language": "en"
    },
    {
      "id": "57214",
      "release_date": "2012-03-01",
      "trailer": "https://www.youtube.com/embed/l5m4bPQLPZ8",
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//lUPDGT3lyRrq8SvWuNWG2DP64bR.jpg",
      "vote_average": 6.8,
      "popularity": 250.459,
      "title": "Project X",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//5vAv4h4vugleYsbsNkUb9kcrk8h.jpg",
      "adult": false,
      "genre": "Comedy",
      "plot": "Three high school seniors throw a party to make a name for themselves. As the night progresses, things spiral out of control as word of the party spreads."
    },
    {
      "id": "573531",
      "release_date": "2010-02-16",
      "popularity": 264.673,
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//zOOKJyRIcjPC1S8xmNEgy2luAXi.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//cO3iAp2pPNdWE9eqS4pTEY5HghY.jpg",
      "title": "Halo Legends",
      "vote_average": 7.3,
      "genre": "Animation",
      "adult": false,
      "plot": "The universe of the Halo video game series is expanded in seven short animated films from Japan's greatest anime directors and studios.",
      "trailer": "https://www.youtube.com/embed/aicPLFajPiU"
    },
    {
      "id": "580489",
      "vote_average": 7.1,
      "release_date": "2021-09-30",
      "adult": false,
      "title": "Venom: Let There Be Carnage",
      "poster_path": "https://image.tmdb.org/t/p/w500//rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
      "trailer": "https://www.youtube.com/embed/GVwq2HlKYpE",
      "popularity": 980.905,
      "plot": "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
      "genre": "Science Fiction",
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg"
    },
    {
      "id": "581726",
      "release_date": "2021-09-09",
      "title": "Infinite",
      "original_language": "en",
      "popularity": 381.198,
      "adult": false,
      "trailer": "https://www.youtube.com/embed/a3RDnD9YVxA",
      "genre": "Science Fiction",
      "vote_average": 6.8,
      "poster_path": "https://image.tmdb.org/t/p/w500//niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
      "plot": "Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//fyxNrfrFcobLuNCufMhNkQuWorX.jpg"
    },
    {
      "id": "585083",
      "release_date": "2022-02-25",
      "adult": false,
      "genre": "Animation",
      "vote_average": 7.1,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//qBLEWvJNVsehJkEJqIigPsWyBse.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//teCy1egGQa0y8ULJvlrDHQKnxBL.jpg",
      "trailer": "https://www.youtube.com/embed/6suJohjIvfo",
      "popularity": 1149.71,
      "plot": "When Van Helsing's mysterious invention, the \"Monsterfication Ray,\" goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it's too late, and before they drive each other crazy.",
      "original_language": "en",
      "title": "Hotel Transylvania: Transformania"
    },
    {
      "id": "585245",
      "release_date": "2021-11-10",
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//oifhfVhUcuDjE61V5bS5dfShQrm.jpg",
      "genre": "Family",
      "vote_average": 7.3,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//1Wlwnhn5sXUIwlxpJgWszT622PS.jpg",
      "plot": "As Emily struggles to fit in at home and at school, she discovers a small red puppy who is destined to become her best friend. When Clifford magically undergoes one heck of a growth spurt, becomes a gigantic dog and attracts the attention of a genetics company, Emily and her Uncle Casey have to fight the forces of greed as they go on the run across New York City. Along the way, Clifford affects the lives of everyone around him and teaches Emily and her uncle the true meaning of acceptance and unconditional love.",
      "title": "Clifford the Big Red Dog",
      "adult": false,
      "popularity": 526.941,
      "trailer": "https://www.youtube.com/embed/PsE3aHTkQYk"
    },
    {
      "id": "588228",
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg",
      "plot": "The world is stunned when a group of time travelers arrive from the year 2051 to deliver an urgent message: Thirty years in the future, mankind is losing a global war against a deadly alien species. The only hope for survival is for soldiers and civilians from the present to be transported to the future and join the fight. Among those recruited is high school teacher and family man Dan Forester. Determined to save the world for his young daughter, Dan teams up with a brilliant scientist and his estranged father in a desperate quest to rewrite the fate of the planet.",
      "trailer": "https://www.youtube.com/embed/RQjEbkV-9ZM",
      "release_date": "2021-07-02",
      "adult": false,
      "title": "The Tomorrow War",
      "poster_path": "https://image.tmdb.org/t/p/w500//34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg",
      "popularity": 285.399,
      "vote_average": 8,
      "genre": "Action"
    },
    {
      "id": "589754",
      "trailer": "https://www.youtube.com/embed/qwt_aDkW5RE",
      "poster_path": "https://image.tmdb.org/t/p/w500//4qE7mvUYGY5epfcgeJpM6EfHgq5.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//dIibeeq4QMay5bTJ2vjr72IFFRo.jpg",
      "vote_average": 7.2,
      "plot": "Peace and tranquility have set in Belogorie. The evil was defeated and Ivan is now enjoying his well-deserved fame. He is surrounded by his family, friends and small wonders from the modern world that help him lead a comfortable life. Luckily, he has his Magic Sword to cut a gap between the worlds to get some supplies quite regularly. But when an ancient evil rises and the existence of the magic world is put to danger, Ivan has to team up with his old friends and his new rivals. They will set out on a long journey beyond the known world to find a way to defeat the enemies and to return peace to Belogorie.",
      "genre": "Fantasy",
      "release_date": "2021-01-01",
      "title": "The Last Warrior: Root of Evil",
      "adult": false,
      "popularity": 345.449,
      "original_language": "ru"
    },
    {
      "id": "589761",
      "vote_average": 6.2,
      "trailer": "https://www.youtube.com/embed/G8xJb6-ZNKM",
      "adult": false,
      "title": "Chernobyl: Abyss",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//xGrTm3J0FTafmuQ85vF7ZCw94x6.jpg",
      "genre": "Drama",
      "plot": "The aftermath of a shocking explosion at the Chernobyl nuclear power station made hundreds of people sacrifice their lives to clean up the site of the catastrophe and to successfully prevent an even bigger disaster that could have turned a large part of the European continent into an uninhabitable exclusion zone. This is their story.",
      "original_language": "ru",
      "popularity": 432.794,
      "release_date": "2021-04-15",
      "poster_path": "https://image.tmdb.org/t/p/w500//AmJLuHjxPdIJO6vmymeWADG6jK5.jpg"
    },
    {
      "id": "592508",
      "popularity": 265.551,
      "genre": "Action",
      "plot": "A fearless, faithful albeit slightly forgetful Mumbai cop, Veer Sooryavanshi, the chief of the Anti-Terrorism Squad in India pulls out all the stops and stunts to thwart a major conspiracy to attack his city.",
      "original_language": "hi",
      "release_date": "2021-11-05",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//7w06baRS9VPm5RYz8lawTCLiR4j.jpg",
      "vote_average": 5.9,
      "poster_path": "https://image.tmdb.org/t/p/w500//8p3mhjyLjHKtaAv8tFKfvEBtir0.jpg",
      "adult": false,
      "trailer": "https://www.youtube.com/embed/u5r77-OQwa8",
      "title": "Sooryavanshi"
    },
    {
      "id": "597208",
      "adult": false,
      "release_date": "2021-12-02",
      "original_language": "en",
      "popularity": 835.281,
      "plot": "An ambitious carnival man with a talent for manipulating people with a few well-chosen words hooks up with a female psychiatrist who is even more dangerous than he is.",
      "vote_average": 7.1,
      "title": "Nightmare Alley",
      "poster_path": "https://image.tmdb.org/t/p/w500//680klE0dIreQQOyWKFgNnCAJtws.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//mqDnDhG5N6fn1H4MKQqr8E5wfeK.jpg",
      "trailer": "https://www.youtube.com/embed/Q81Yf46Oj3s",
      "genre": "Crime"
    },
    {
      "id": "614917",
      "trailer": "https://www.youtube.com/embed/_6bsugyNpDU",
      "adult": false,
      "title": "King Richard",
      "genre": "Drama",
      "original_language": "en",
      "plot": "The story of how Richard Williams served as a coach to his daughters Venus and Serena, who will soon become two of the most legendary tennis players in history.",
      "vote_average": 7.9,
      "release_date": "2021-11-18",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//95SwyPKoWGK35zOnAjikra7OFIQ.jpg",
      "popularity": 248.567,
      "poster_path": "https://image.tmdb.org/t/p/w500//2dfujXrxePtYJPiPHj1HkAFQvpu.jpg"
    },
    {
      "id": "615904",
      "release_date": "2022-02-09",
      "vote_average": 6.9,
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//koaxq5QbARIlfxCOR89atPHv367.jpg",
      "title": "Marry Me",
      "plot": "Music superstars Kat Valdez and Bastian are getting married before a global audience of fans. But when Kat learns, seconds before her vows, that Bastian has been unfaithful, she decides to marry Charlie, a stranger in the crowd, instead.",
      "poster_path": "https://image.tmdb.org/t/p/w500//ko1JVbGj4bT8IhCWqjBQ6ZtF2t.jpg",
      "trailer": "https://www.youtube.com/embed/Ebv9_rNb5Ig",
      "genre": "Romance",
      "popularity": 407.255,
      "original_language": "en"
    },
    {
      "id": "617653",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//mFbS5TwN95BcSEfiztdchLgTQ0v.jpg",
      "original_language": "en",
      "genre": "Action",
      "adult": false,
      "plot": "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire, Jacques Le Gris, by challenging him to a duel.",
      "title": "The Last Duel",
      "poster_path": "https://image.tmdb.org/t/p/w500//zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg",
      "vote_average": 7.6,
      "release_date": "2021-10-13",
      "trailer": "https://www.youtube.com/embed/mgygUwPJvYk",
      "popularity": 280.07
    },
    {
      "id": "619979",
      "poster_path": "https://image.tmdb.org/t/p/w500//6yRMyWwjuhKg6IU66uiZIGhaSc8.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//hJjA3EY7yoT1djGyD20lM3WzgyM.jpg",
      "trailer": "https://www.youtube.com/embed/90JsrQwE5CA",
      "plot": "Vic and Melinda Van Allen are a couple in the small town of Little Wesley. Their loveless marriage is held together only by a precarious arrangement whereby, in order to avoid the messiness of divorce, Melinda is allowed to take any number of lovers as long as she does not desert her family.",
      "adult": false,
      "popularity": 661.175,
      "genre": "Drama",
      "release_date": "2022-03-18",
      "vote_average": 5.5,
      "title": "Deep Water",
      "original_language": "en"
    },
    {
      "id": "624860",
      "popularity": 677.998,
      "plot": "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
      "title": "The Matrix Resurrections",
      "adult": false,
      "genre": "Science Fiction",
      "release_date": "2021-12-16",
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
      "trailer": "https://www.youtube.com/embed/nNpvWBuTfrc",
      "poster_path": "https://image.tmdb.org/t/p/w500//8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
      "vote_average": 6.8
    },
    {
      "id": "629542",
      "original_language": "en",
      "genre": "Animation",
      "plot": "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
      "adult": false,
      "release_date": "2022-03-17",
      "popularity": 620.426,
      "vote_average": 7.6,
      "title": "The Bad Guys",
      "poster_path": "https://image.tmdb.org/t/p/w500//7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
      "trailer": "https://www.youtube.com/embed/zpDuBXB_glk",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//fEe5fe82qHzjO4yej0o79etqsWV.jpg"
    },
    {
      "id": "631843",
      "plot": "A group of families on a tropical holiday discover that the secluded beach where they are staying is somehow causing them to age rapidly – reducing their entire lives into a single day.",
      "vote_average": 6.6,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//iTgM25ftE7YtFgZwUZupVp8A61S.jpg",
      "release_date": "2021-07-21",
      "adult": false,
      "genre": "Thriller",
      "original_language": "en",
      "title": "Old",
      "trailer": "https://www.youtube.com/embed/A4U2pMRV9_k",
      "poster_path": "https://image.tmdb.org/t/p/w500//vclShucpUmPhdAOmKgf3B3Z4POD.jpg",
      "popularity": 284.791
    },
    {
      "id": "632727",
      "adult": false,
      "title": "Texas Chainsaw Massacre",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//aTSA5zMWlVFTYBIZxTCMbLkfOtb.jpg",
      "vote_average": 5.2,
      "plot": "In this sequel, influencers looking to breathe new life into a Texas ghost town encounter Leatherface, an infamous killer who wears a mask of human skin.",
      "genre": "Horror",
      "trailer": "https://www.youtube.com/embed/zcI6SFiK_yk",
      "release_date": "2022-02-18",
      "poster_path": "https://image.tmdb.org/t/p/w500//meRIRfADEGVo65xgPO6eZvJ0CRG.jpg",
      "popularity": 599.55,
      "original_language": "en"
    },
    {
      "id": "633802",
      "genre": "Romance",
      "vote_average": 6.7,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//o2OSpKzXuB1edCDyVC2MXAxXwyJ.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//2AbGdSGlU6CpiV3lswHUgE5CdAA.jpg",
      "release_date": "2021-02-11",
      "trailer": "https://www.youtube.com/embed/kR0RVnMbnOM",
      "plot": "Terror strikes when a heartbroken woman uses black magic to get her husband back.",
      "adult": false,
      "title": "Dark Spell",
      "popularity": 251.395,
      "original_language": "ru"
    },
    {
      "id": "634649",
      "adult": false,
      "poster_path": "https://image.tmdb.org/t/p/w500//1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
      "original_language": "en",
      "vote_average": 8.2,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
      "plot": "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
      "title": "Spider-Man: No Way Home",
      "trailer": "https://www.youtube.com/embed/pBvH8hvnJPk",
      "genre": "Action",
      "release_date": "2021-12-15",
      "popularity": 6064.019
    },
    {
      "id": "635302",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//qjGrUmKW78MCFG8PTLDBp67S27p.jpg",
      "release_date": "2020-10-16",
      "original_language": "ja",
      "trailer": "https://www.youtube.com/embed/XbTSLJ62YEM",
      "vote_average": 8.4,
      "popularity": 883.742,
      "adult": false,
      "plot": "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
      "title": "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
      "genre": "Animation",
      "poster_path": "https://image.tmdb.org/t/p/w500//h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg"
    },
    {
      "id": "637649",
      "plot": "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
      "title": "Wrath of Man",
      "trailer": "https://www.youtube.com/embed/wo1kO8m2Nik",
      "poster_path": "https://image.tmdb.org/t/p/w500//M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//70AV2Xx5FQYj20labp0EGdbjI6E.jpg",
      "genre": "Action",
      "adult": false,
      "vote_average": 7.7,
      "popularity": 276.083,
      "original_language": "en",
      "release_date": "2021-04-22"
    },
    {
      "id": "646385",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//g3UTK29RMThW0OIvWTLDfSPCHSV.jpg",
      "genre": "Horror",
      "adult": false,
      "poster_path": "https://image.tmdb.org/t/p/w500//kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg",
      "vote_average": 6.8,
      "plot": "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
      "title": "Scream",
      "popularity": 775.204,
      "trailer": "https://www.youtube.com/embed/nRwLyKIBNU8",
      "release_date": "2022-01-12",
      "original_language": "en"
    },
    {
      "id": "656663",
      "adult": false,
      "genre": "Action",
      "popularity": 920.893,
      "original_language": "en",
      "release_date": "2022-02-01",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//f2J8DpT5bqV0AiI9VVcfiuqKo5l.jpg",
      "plot": "Celebrate the joy of a perfectly executed shot to the groin as Johnny Knoxville, Steve-O and the rest of the gang return alongside some newcomers for one final round of hilarious, wildly absurd and often dangerous displays of stunts and comedy.",
      "title": "Jackass Forever",
      "vote_average": 7,
      "trailer": "https://www.youtube.com/embed/p74bzf-beGc",
      "poster_path": "https://image.tmdb.org/t/p/w500//ugIdyvtAzHWOguD91UjHKoAvfum.jpg"
    },
    {
      "id": "675353",
      "vote_average": 7.8,
      "plot": "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
      "popularity": 3032.171,
      "title": "Sonic the Hedgehog 2",
      "original_language": "en",
      "genre": "Action",
      "release_date": "2022-03-30",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
      "trailer": "https://www.youtube.com/embed/47r8FXYZWNU",
      "adult": false,
      "poster_path": "https://image.tmdb.org/t/p/w500//6DrHO1jr3qVrViUO6s6kFiAGM7.jpg"
    },
    {
      "id": "675445",
      "trailer": "https://www.youtube.com/embed/LRMTr2VZcr8",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//a17F3zXnmuwqxfiDa46mtlosjrv.jpg",
      "genre": "Animation",
      "plot": "Ryder and the pups are called to Adventure City to stop Mayor Humdinger from turning the bustling metropolis into a state of chaos.",
      "release_date": "2021-08-09",
      "adult": false,
      "title": "PAW Patrol: The Movie",
      "vote_average": 7.5,
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//ic0intvXZSfBlYPIvWXpU1ivUCO.jpg",
      "popularity": 396.418
    },
    {
      "id": "676705",
      "title": "Pil's Adventures",
      "vote_average": 6.8,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//tq3klWQevRK0Or0cGhsw0h3FDWQ.jpg",
      "popularity": 1664.778,
      "poster_path": "https://image.tmdb.org/t/p/w500//abPQVYyNfVuGoFUfGVhlNecu0QG.jpg",
      "original_language": "fr",
      "genre": "Adventure",
      "plot": "Pil, a little vagabond girl, lives on the streets of the medieval city of Roc-en-Brume, along with her three tame weasels. She survives of food stolen from the castle of the sinister Regent Tristain. One day, to escape his guards, Pil disguises herself as a princess. Thus she embarks upon a mad, delirious adventure, together with Crobar, a big clumsy guard who thinks she's a noble, and Rigolin, a young crackpot jester. Pil is going to have to save Roland, rightful heir to the throne under the curse of a spell. This adventure will turn the entire kingdom upside down, and teach Pil that nobility can be found in all of us.",
      "release_date": "2021-08-11",
      "trailer": "https://www.youtube.com/embed/4A0muKc83Nc",
      "adult": false
    },
    {
      "id": "685274",
      "trailer": "https://www.youtube.com/embed/MzxnPP5TLeU",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//mI0Qo7VtgW5siCtQQqNPXIk0Ar6.jpg",
      "vote_average": 7.8,
      "genre": "Animation",
      "popularity": 320.655,
      "title": "Mobile Suit Gundam Hathaway",
      "poster_path": "https://image.tmdb.org/t/p/w500//6gw8onh4FKsruBA7Oouv01EFxzn.jpg",
      "original_language": "ja",
      "release_date": "2021-06-11",
      "adult": false,
      "plot": "After Char's rebellion, Hathaway Noa leads an insurgency against Earth Federation, but meeting an enemy officer and a mysterious woman alters his fate."
    },
    {
      "id": "691683",
      "adult": false,
      "trailer": "https://www.youtube.com/embed/Wq8Nsc5r2So",
      "vote_average": 6.2,
      "popularity": 370.399,
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//qNRsouZh5zmhaE3n4QpLDXzy1gQ.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//mHTzTYdoiUS1YmiZ9BZKd3nS4qk.jpg",
      "genre": "Family",
      "release_date": "2022-03-18",
      "plot": "This remake of the beloved classic follows the raucous exploits of a blended family of 12, the Bakers, as they navigate a hectic home life while simultaneously managing their family business.",
      "title": "Cheaper by the Dozen"
    },
    {
      "id": "696806",
      "plot": "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.",
      "poster_path": "https://image.tmdb.org/t/p/w500//wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
      "popularity": 2289.346,
      "title": "The Adam Project",
      "genre": "Action",
      "vote_average": 7,
      "original_language": "en",
      "release_date": "2022-03-11",
      "trailer": "https://www.youtube.com/embed/IE8HIsIrq4o",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//ewUqXnwiRLhgmGhuksOdLgh49Ch.jpg",
      "adult": false
    },
    {
      "id": "703771",
      "popularity": 353.528,
      "release_date": "2020-08-04",
      "trailer": "https://www.youtube.com/embed/MsdVLe2xi9g",
      "genre": "Animation",
      "original_language": "en",
      "title": "Deathstroke: Knights & Dragons - The Movie",
      "vote_average": 6.9,
      "adult": false,
      "plot": "The assassin Deathstroke tries to save his family from the wrath of H.I.V.E. and the murderous Jackal.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//hdXQxlD4mep7qtC5TsvhIt840OV.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//vFIHbiy55smzi50RmF8LQjmpGcx.jpg"
    },
    {
      "id": "726684",
      "release_date": "2021-05-15",
      "genre": "Animation",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//rlNnwObbMu5G2FaOUlacnUIdIIA.jpg",
      "adult": false,
      "popularity": 314.274,
      "poster_path": "https://image.tmdb.org/t/p/w500//qQ0VKsGRQ2ofAmswGNzZnvC1xPE.jpg",
      "original_language": "fr",
      "title": "Miraculous World: Shanghai – The Legend of Ladydragon",
      "trailer": "https://www.youtube.com/embed/TF63WzwuBcM",
      "plot": "On school break, Marinette heads to Shanghai to meet Adrien. But after arriving, Marinette loses all her stuff, including the Miraculous that allows her to turn into Ladybug!",
      "vote_average": 7.9
    },
    {
      "id": "739413",
      "plot": "Georgia and her boyfriend Sam go on a treacherous journey to escape their country, which is caught in an unexpected war with artificial intelligence. Days away from the arrival of their first child, the couple must face No Man’s Land—a stronghold of the android uprising—in hopes of reaching safety before giving birth.",
      "popularity": 349.476,
      "poster_path": "https://image.tmdb.org/t/p/w500//rO3nV9d1wzHEWsC7xgwxotjZQpM.jpg",
      "adult": false,
      "trailer": "https://www.youtube.com/embed/JRl214mDZ-g",
      "genre": "Science Fiction",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//AmLpWYm9R3Ur2FLPgj5CH3wR8wp.jpg",
      "release_date": "2021-12-17",
      "original_language": "en",
      "vote_average": 5.9,
      "title": "Mother/Android"
    },
    {
      "id": "744275",
      "trailer": "https://www.youtube.com/embed/NYdNN6C9hfI",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//lV3UFPPxDIPelh46G9oySXN9Mcz.jpg",
      "release_date": "2021-09-01",
      "plot": "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
      "adult": false,
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//dU4HfnTEJDf9KvxGS9hgO7BVeju.jpg",
      "popularity": 361.683,
      "title": "After We Fell",
      "vote_average": 7.2,
      "genre": "Romance"
    },
    {
      "id": "753232",
      "original_language": "en",
      "popularity": 897.081,
      "title": "The Commando",
      "adult": false,
      "vote_average": 6.6,
      "plot": "An elite DEA agent returns home after a failed mission when his family makes an unexpected discovery in their house – a stash of money worth $3 million. They soon face the danger and threat of a newly released criminal and his crew, who will do whatever it takes to retrieve the money, including kidnap the agent’s daughters. Stakes are high and lives are at risk in this head-to-head battle as the agent stops at nothing to protect his family against the money-hungry criminals.",
      "genre": "Action",
      "release_date": "2022-01-07",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//pnZ9NMxRqbcJ2dPNROIoregruv5.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//mvCVaas7FkRV8uvyIJl1ANdT28k.jpg",
      "trailer": "https://www.youtube.com/embed/_EoLNs5m-7Y"
    },
    {
      "id": "760868",
      "genre": "Action",
      "release_date": "2022-03-18",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//t7I942V5U1Ggn6OevN75u3sNYH9.jpg",
      "popularity": 2253.382,
      "vote_average": 6.1,
      "plot": "To end an apocalyptic war and save her daughter, a reluctant soldier embarks on a desperate mission to cross a frozen sea carrying a top-secret cargo.",
      "trailer": "https://www.youtube.com/embed/fmjKsL_-rfw",
      "adult": false,
      "original_language": "sv",
      "title": "Black Crab",
      "poster_path": "https://image.tmdb.org/t/p/w500//mcIYHZYwUbvhvUt8Lb5nENJ7AlX.jpg"
    },
    {
      "id": "760926",
      "release_date": "2022-01-13",
      "genre": "Thriller",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//yzH5zvuEzzsHLZnn0jwYoPf0CMT.jpg",
      "vote_average": 6.5,
      "poster_path": "https://image.tmdb.org/t/p/w500//ejXBuNLvK4kZ7YcqeKqUWnCxdJq.jpg",
      "original_language": "en",
      "trailer": "https://www.youtube.com/embed/1HqBaI-FV7Y",
      "plot": "In the not-too-distant future, two drifters traveling through the desert stumble across the biggest gold nugget ever found and the dream of immense wealth and greed takes hold. They hatch a plan to excavate their bounty, with one man leaving to secure the necessary tools while the other remains with the gold. The man who remains must endure harsh desert elements, ravenous wild dogs, and mysterious intruders, while battling the sinking suspicion that he has been abandoned to his fate.",
      "title": "Gold",
      "popularity": 1413.982,
      "adult": false
    },
    {
      "id": "762433",
      "plot": "Called to Rome to stop an imminent terrorist bombing, a soldier desperately seeks news of his imprisoned brother — a rebel with knowledge that could thwart the attack. Navigating the capital's darkened streets, he races to a series of ominous encounters to keep the Vatican from being blown to bits.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//wnn2Zf1ZuCgcCVaoNdp20OI2uTs.jpg",
      "genre": "Thriller",
      "title": "Zeros and Ones",
      "adult": false,
      "release_date": "2021-11-18",
      "poster_path": "https://image.tmdb.org/t/p/w500//a6balsDWCFMHPaPT6rFoBpNjR6z.jpg",
      "popularity": 267.814,
      "original_language": "en",
      "trailer": "https://www.youtube.com/embed/RHje2IaqZGg",
      "vote_average": 5.3
    },
    {
      "id": "763164",
      "release_date": "2021-11-12",
      "genre": "Action",
      "popularity": 271.52,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//4gKxQIW91hOTELjY5lzjMbLoGxB.jpg",
      "trailer": "https://www.youtube.com/embed/Pompk1znaIw",
      "plot": "Ex-cop Thomas Malone is serving a life sentence for a crime he didn’t commit. He is offered a chance at freedom if he can survive a deadly game of Apex, in which six hunters pay for the pleasure of hunting another human on a remote island. He accepts, and once he arrives, all hell breaks loose.",
      "poster_path": "https://image.tmdb.org/t/p/w500//chTkFGToW5bsyw3hgLAe4S5Gt3.jpg",
      "adult": false,
      "vote_average": 5.3,
      "title": "Apex",
      "original_language": "en"
    },
    {
      "id": "763788",
      "poster_path": "https://image.tmdb.org/t/p/w500//vTtkQGC7qKlSRQJZYtAWAmYdH0A.jpg",
      "vote_average": 6.3,
      "plot": "A reformed sociopath heads to a remote island after the death of his brother. Soon after his arrival, the island falls under siege from a deadly gang of mercenaries, and when he discovers their role in his brother’s demise, he sets out on a relentless quest for vengeance.",
      "popularity": 302.344,
      "trailer": "https://www.youtube.com/embed/rFq52e7wYws",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//mo57hzhW3BcZL1f7MNteWKHsmlN.jpg",
      "original_language": "en",
      "title": "Dangerous",
      "genre": "Action",
      "adult": false,
      "release_date": "2021-11-05"
    },
    {
      "id": "766907",
      "original_language": "en",
      "release_date": "2022-01-07",
      "genre": "Action",
      "trailer": "https://www.youtube.com/embed/AdI6ea_0T0s",
      "vote_average": 5.4,
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//vsN9Lpi3HQJHQeHx8GzN6qfOYqk.jpg",
      "popularity": 554.31,
      "poster_path": "https://image.tmdb.org/t/p/w500//daeVrgyj0ue8qb3AHyU3UeCwoZz.jpg",
      "title": "American Siege",
      "plot": "An ex-NYPD officer-turned-sheriff of a small rural Georgia town has to contend with a gang of thieves who have taken a wealthy doctor hostage."
    },
    {
      "id": "768744",
      "adult": false,
      "release_date": "2021-08-06",
      "vote_average": 7.4,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//cugmVwK0N4aAcLibelKN5jWDXSx.jpg",
      "genre": "Animation",
      "title": "My Hero Academia: World Heroes' Mission",
      "poster_path": "https://image.tmdb.org/t/p/w500//4NUzcKtYPKkfTwKsLjwNt8nRIXV.jpg",
      "popularity": 1105.809,
      "original_language": "ja",
      "trailer": "https://www.youtube.com/embed/0r4OB67me6I",
      "plot": "A mysterious group called Humarize strongly believes in the Quirk Singularity Doomsday theory which states that when quirks get mixed further in with future generations, that power will bring forth the end of humanity. In order to save everyone, the Pro-Heroes around the world ask UA Academy heroes-in-training to assist them and form a world-classic selected hero team. It is up to the heroes to save the world and the future of heroes in what is the most dangerous crisis to take place yet in My Hero Academia."
    },
    {
      "id": "770254",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//5B22eed7ErxFiYAG4Ksb4eLwKNF.jpg",
      "plot": "Tired of being locked in a reptile house where humans gawk at them like they are monsters, a ragtag group of Australia’s deadliest creatures plot an escape from their zoo to the Outback, a place where they’ll fit in without being judged.",
      "title": "Back to the Outback",
      "poster_path": "https://image.tmdb.org/t/p/w500//zNXNRLH5wJprUG6B1olaBTNZOjy.jpg",
      "popularity": 274.782,
      "adult": false,
      "vote_average": 7.7,
      "original_language": "en",
      "trailer": "https://www.youtube.com/embed/dDNhtB7L8Lk",
      "release_date": "2021-12-03",
      "genre": "Animation"
    },
    {
      "id": "774741",
      "adult": false,
      "title": "Diary of a Wimpy Kid",
      "trailer": "https://www.youtube.com/embed/VKhCPUa-glo",
      "vote_average": 6.5,
      "release_date": "2021-12-03",
      "plot": "Greg Heffley is a scrawny but ambitious kid with an active imagination and big plans to be rich and famous – he just has to survive middle school first.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//x78cvxbmpBNcHON7x3Iv8vih5Sj.jpg",
      "genre": "Animation",
      "popularity": 327.544,
      "poster_path": "https://image.tmdb.org/t/p/w500//obg6lWuNaZkoSlwrVG4VVk4SmT.jpg",
      "original_language": "en"
    },
    {
      "id": "774825",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//eG0oOQVsniPAuecPzDD1B1gnYWy.jpg",
      "popularity": 1199.339,
      "vote_average": 7,
      "original_language": "en",
      "genre": "Animation",
      "plot": "The fearless one-eyed weasel Buck teams up with mischievous possum brothers Crash & Eddie as they head off on a new adventure into Buck's home: The Dinosaur World.",
      "trailer": "https://www.youtube.com/embed/0U0L4uT0btQ",
      "adult": false,
      "release_date": "2022-01-28",
      "title": "The Ice Age Adventures of Buck Wild",
      "poster_path": "https://image.tmdb.org/t/p/w500//zzXFM4FKDG7l1ufrAkwQYv2xvnh.jpg"
    },
    {
      "id": "776503",
      "popularity": 293.356,
      "plot": "As a CODA (Child of Deaf Adults), Ruby is the only hearing person in her deaf family. When the family's fishing business is threatened, Ruby finds herself torn between pursuing her love of music and her fear of abandoning her parents.",
      "vote_average": 8.1,
      "poster_path": "https://image.tmdb.org/t/p/w500//BzVjmm8l23rPsijLiNLUzuQtyd.jpg",
      "genre": "Drama",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//v85FlkbMYKa5du1glm0YfYNsL2n.jpg",
      "trailer": "https://www.youtube.com/embed/0pmfrE1YL4I",
      "release_date": "2021-08-11",
      "original_language": "en",
      "adult": false,
      "title": "CODA"
    },
    {
      "id": "787310",
      "plot": "When cop David is injured in a drug bust gone wrong, his partner Cal chases the two criminals who shot him. They all land at a remote farm owned by troubled vet Eric, and as Cal and Eric plot their defense, more of the gang arrives - along with a wounded David. Outnumbered, the three heroes must use stealth, smarts, and good shooting to take down the drug-dealing mob.",
      "original_language": "en",
      "title": "Survive the Game",
      "vote_average": 5.8,
      "release_date": "2021-10-08",
      "trailer": "https://www.youtube.com/embed/AqmOsnSElnw",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//7esxXkFyl0dVD7ViR0Q6fK5VeXB.jpg",
      "adult": false,
      "genre": "Action",
      "popularity": 237.467,
      "poster_path": "https://image.tmdb.org/t/p/w500//xF1uc2pEf34X2G41wvZaF5H0V7C.jpg"
    },
    {
      "id": "791373",
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
      "trailer": "https://www.youtube.com/embed/ZrdQSAX2kyw",
      "popularity": 374.892,
      "plot": "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
      "adult": false,
      "vote_average": 8.3,
      "genre": "Action",
      "release_date": "2021-03-18",
      "title": "Zack Snyder's Justice League",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg"
    },
    {
      "id": "795514",
      "plot": "In the wake of a school tragedy, Vada, Mia and Quinton form a unique and dynamic bond as they navigate the never linear, often confusing journey to heal in a world that feels forever changed.",
      "title": "The Fallout",
      "adult": false,
      "original_language": "en",
      "vote_average": 7.5,
      "trailer": "https://www.youtube.com/embed/Gtl-6RCOl84",
      "poster_path": "https://image.tmdb.org/t/p/w500//y94auaBWq1E7sun3ZpvBmQfGUW.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//lMWOcXVA62xnk1jSaz8iwrxVJR7.jpg",
      "genre": "Drama",
      "popularity": 318.983,
      "release_date": "2021-03-17"
    },
    {
      "id": "796499",
      "adult": false,
      "genre": "Crime",
      "release_date": "2021-10-27",
      "original_language": "en",
      "popularity": 255.853,
      "plot": "A mysterious woman recruits bank teller Ludwig Dieter to lead a group of aspiring thieves on a top-secret heist during the early stages of the zombie apocalypse.",
      "trailer": "https://www.youtube.com/embed/Ith2WetKXlg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//mu8RKavbv7Ml48twHQ6XVk7zw8e.jpg",
      "title": "Army of Thieves",
      "vote_average": 6.9,
      "poster_path": "https://image.tmdb.org/t/p/w500//iPTZGFmPs7HsXHYxiuxGolihjOH.jpg"
    },
    {
      "id": "800510",
      "poster_path": "https://image.tmdb.org/t/p/w500//okNgwtxIWzGsNlR3GsOS0i0Qgbn.jpg",
      "release_date": "2022-02-10",
      "vote_average": 6.2,
      "trailer": "https://www.youtube.com/embed/67S8ru4K4x4",
      "popularity": 1150.563,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//mruT954ve6P1zquaRs6XG0hA5k9.jpg",
      "adult": false,
      "original_language": "en",
      "plot": "A tech worker with agoraphobia discovers recorded evidence of a violent crime but is met with resistance when she tries to report it. Seeking justice, she must do the thing she fears the most: she must leave her apartment.",
      "title": "Kimi",
      "genre": "Thriller"
    },
    {
      "id": "801071",
      "plot": "When a vintage Jack-in-the-box is opened by a dying woman, she enters into a deal with the demon within that would see her illness cured in return for helping it claim six innocent victims.",
      "release_date": "2022-02-24",
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//xHRabofjmMGoIV3mb6xgy4nwOcS.jpg",
      "title": "The Jack in the Box: Awakening",
      "adult": false,
      "popularity": 891.832,
      "vote_average": 5.8,
      "poster_path": "https://image.tmdb.org/t/p/w500//3Ib8vlWTrAKRrTWUrTrZPOMW4jp.jpg",
      "genre": "Horror",
      "trailer": "https://www.youtube.com/embed/7InYvYQq8DU"
    },
    {
      "id": "803104",
      "genre": "Comedy",
      "title": "Sex Appeal",
      "original_language": "en",
      "trailer": "https://www.youtube.com/embed/A207HN4bRJM",
      "vote_average": 7,
      "release_date": "2022-01-14",
      "plot": "Avery, a teenager with a tendency towards perfectionism, enlists her friend Larson to help her prepare for her first time with her long-distance boyfriend.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//sqLNgWTMBhLBRY26SwwfWcSI5qq.jpg",
      "adult": false,
      "popularity": 572.294,
      "poster_path": "https://image.tmdb.org/t/p/w500//mpwXOeSSQdBjUpyQqf6YHYbSTFO.jpg"
    },
    {
      "id": "803114",
      "genre": "Thriller",
      "plot": "A couple on a romantic getaway find themselves stranded at sea when a tropical storm sweeps away their villa. In order to survive, they are forced to fight the elements, while sharks circle below.",
      "adult": false,
      "popularity": 1057.894,
      "poster_path": "https://image.tmdb.org/t/p/w500//i0z8g2VRZP3dhVvvSMilbOZMKqR.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//eVSa4TpyXbOdk9fXSD6OcORJGtv.jpg",
      "release_date": "2022-01-28",
      "title": "The Requin",
      "original_language": "en",
      "trailer": "https://www.youtube.com/embed/kWXK5fibfko",
      "vote_average": 4.8
    },
    {
      "id": "810693",
      "genre": "Animation",
      "popularity": 587.212,
      "original_language": "ja",
      "title": "Jujutsu Kaisen 0",
      "poster_path": "https://image.tmdb.org/t/p/w500//3pTwMUEavTzVOh6yLN0aEwR7uSy.jpg",
      "plot": "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//geYUecpFI2AonDLhjyK9zoVFcMv.jpg",
      "vote_average": 7.8,
      "release_date": "2021-12-24",
      "trailer": "https://www.youtube.com/embed/2docezZl574"
    },
    {
      "id": "811592",
      "vote_average": 6.8,
      "genre": "Action",
      "release_date": "2021-11-05",
      "plot": "An elite squad of Navy SEALs, on a covert mission to transport a prisoner off a CIA black site island prison, are trapped when insurgents attack while trying to rescue the same prisoner.",
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//3OXiTjU30gWtqxmx4BU9RVp2OTv.jpg",
      "adult": false,
      "popularity": 432.493,
      "title": "One Shot",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//srJ7haOhfykoPOYPQrstOaFem08.jpg",
      "trailer": "https://www.youtube.com/embed/Et5Cgq1B2_g"
    },
    {
      "id": "818647",
      "release_date": "2022-02-04",
      "trailer": "https://www.youtube.com/embed/_zxhK3Z-R0c",
      "genre": "Romance",
      "vote_average": 7.7,
      "plot": "Raquel's longtime crush on her next-door neighbor turns into something more when he starts developing feelings for her, despite his family's objections.",
      "adult": false,
      "popularity": 451.422,
      "original_language": "es",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//4rsomWxlqnHt3muGYK06auhOib6.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//6gg7fvKc1ZxP9yCczweSxIGYp4S.jpg",
      "title": "Through My Window"
    },
    {
      "id": "821427",
      "poster_path": "https://image.tmdb.org/t/p/w500//zIkGGiQBNITG9vVxgmf6MXQ1gT1.jpg",
      "trailer": "https://www.youtube.com/embed/Z4zCPgMdbo0",
      "popularity": 386.019,
      "original_language": "en",
      "plot": "A college freshman joins her university's rowing team and undertakes an obsessive physical and psychological journey to make it to the top varsity boat, no matter the cost.",
      "genre": "Drama",
      "title": "The Novice",
      "release_date": "2021-12-17",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//ic8h5oYQWwqQWPyfpZUSomZTdao.jpg",
      "vote_average": 6.6,
      "adult": false
    },
    {
      "id": "823625",
      "genre": "Action",
      "title": "Blacklight",
      "adult": false,
      "plot": "Travis Block is a shadowy Government agent who specializes in removing operatives whose covers have been exposed. He then has to uncover a deadly conspiracy within his own ranks that reaches the highest echelons of power.",
      "poster_path": "https://image.tmdb.org/t/p/w500//bv9dy8mnwftdY2j6gG39gCfSFpV.jpg",
      "trailer": "https://www.youtube.com/embed/k_N9pU4FMOs",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//2hGjmgZrS1nlsEl5PZorn7EsmzH.jpg",
      "release_date": "2022-02-10",
      "vote_average": 6,
      "popularity": 1932.649,
      "original_language": "en"
    },
    {
      "id": "826749",
      "plot": "The story revolves around a top-secret resort for retired U.S. intelligence officers. A group of criminals led by Balzary breach the compound, hellbent on revenge on Robert, forcing the retired officer and his son to save the day.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//nV905JQSBo0a6zW8UmmmhDj0fQj.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//vQxtoPJVfpHgL7DCg9hQFZKDWJa.jpg",
      "vote_average": 6.3,
      "trailer": "https://www.youtube.com/embed/LdqK7CuCYp4",
      "release_date": "2021-12-17",
      "title": "Fortress",
      "adult": false,
      "genre": "Crime",
      "popularity": 247.137,
      "original_language": "en"
    },
    {
      "id": "829358",
      "poster_path": "https://image.tmdb.org/t/p/w500//4IKBzVBPLXu9p5cfEfdJjHdlafV.jpg",
      "genre": "Horror",
      "original_language": "en",
      "adult": false,
      "release_date": "2021-06-11",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//5UANdP8xXHyVOGknfJlzQ7muLj3.jpg",
      "plot": "According to legend, an ominous entity known as the Queen of Spades can be summoned by performing an ancient ritual. Four teenagers summon the Queen of Spades, but they could never imagine the horrors that await them.",
      "title": "Queen of Spades",
      "popularity": 345.906,
      "trailer": "https://www.youtube.com/embed/99rqjAbDfYU",
      "vote_average": 6.3
    },
    {
      "id": "833425",
      "original_language": "en",
      "trailer": "https://www.youtube.com/embed/GFvupyiNEz0",
      "vote_average": 6.5,
      "release_date": "2022-02-25",
      "adult": false,
      "plot": "Stranded at a rest stop in the mountains during a blizzard, a recovering addict discovers a kidnapped child hidden in a car belonging to one of the people inside the building which sets her on a terrifying struggle to identify who among them is the kidnapper.",
      "poster_path": "https://image.tmdb.org/t/p/w500//5cnLoWq9o5tuLe1Zq4BTX4LwZ2B.jpg",
      "title": "No Exit",
      "genre": "Horror",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//33wnBK5NxvuKQv0Cxo3wMv0eR7F.jpg",
      "popularity": 1538.795
    },
    {
      "id": "836225",
      "adult": false,
      "trailer": "https://www.youtube.com/embed/VdLI8I4jZD0",
      "popularity": 335.472,
      "vote_average": 6.6,
      "release_date": "2022-02-10",
      "title": "The Exorcism of God",
      "plot": "An American priest working in Mexico is considered a saint by many local parishioners. However, due to a botched exorcism, he carries a secret that’s eating him alive until he gets an opportunity to face his demon one final time.",
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//pcqo9D8Bdppt6t9fBliJYPROZkv.jpg",
      "genre": "Horror",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//1RIbsZwmwjOWTR94LxEG7MO48v4.jpg"
    },
    {
      "id": "840882",
      "release_date": "2022-03-03",
      "original_language": "en",
      "poster_path": "https://image.tmdb.org/t/p/w500//6MS0QEl7UK2gdFFbHfNwuYlsq4H.jpg",
      "adult": false,
      "plot": "When her best friend vanishes during a girls' trip to Croatia, Beth races to figure out what happened. But each clue yields another unsettling deception.",
      "title": "The Weekend Away",
      "trailer": "https://www.youtube.com/embed/820j10lEAec",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//isBUqT3hGKvzIoiGcVzURh1EdvQ.jpg",
      "popularity": 437.934,
      "genre": "Thriller",
      "vote_average": 6
    },
    {
      "id": "843241",
      "original_language": "ja",
      "plot": "With the help of the \"Dragon Sin of Wrath\" Meliodas and the worst rebels in history, the Seven Deadly Sins, the \"Holy War\", in which four races, including Humans, Goddesses, Fairies and Giants fought against the Demons, is finally over. At the cost of the \"Lion Sin of Pride\" Escanor's life, the Demon King was defeated and the world regained peace. After that, each of the Sins take their own path.",
      "trailer": "https://www.youtube.com/embed/ryRQCjV7TN8",
      "release_date": "2021-07-02",
      "genre": "Animation",
      "adult": false,
      "poster_path": "https://image.tmdb.org/t/p/w500//k0ThmZQl5nHe4JefC2bXjqtgYp0.jpg",
      "vote_average": 7.9,
      "popularity": 609.776,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//vkjsoMF86dJIv6Sgtd4CcuR8kzh.jpg",
      "title": "The Seven Deadly Sins: Cursed by Light"
    },
    {
      "id": "860623",
      "adult": false,
      "genre": "Action",
      "title": "Last Man Down",
      "plot": "After civilization succumbs to a deadly pandemic and his wife is murdered, a special forces soldier abandons his duty and becomes a hermit in the Nordic wilderness. Years later, a wounded woman appears on his doorstep. She's escaped from a lab and her pursuers believe her blood is the key to a worldwide cure. He's hesitant to get involved, but all doubts are cast aside when he discovers her pursuer is none other than Commander Stone, the man that murdered his wife some years ago.",
      "vote_average": 6.2,
      "poster_path": "https://image.tmdb.org/t/p/w500//4B7liCxNCZIZGONmAMkCnxVlZQV.jpg",
      "release_date": "2021-10-19",
      "trailer": "https://www.youtube.com/embed/Cs5AVa6-M6A",
      "popularity": 851.712,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//t4To8feUSysyBs4tlBAbXIrKlCv.jpg",
      "original_language": "en"
    },
    {
      "id": "870671",
      "adult": false,
      "plot": "When a mysterious animal attack leaves a mutilated body in the forest, a conservative small town detective must enlist the help of an eager wildlife specialist to uncover the dark and disturbing truth that threatens the town.",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//q2KFBGyUSzHDhNqXEYv2LqTWVSz.jpg",
      "popularity": 442.583,
      "vote_average": 5.4,
      "title": "The Hunting",
      "release_date": "2022-01-21",
      "trailer": "https://www.youtube.com/embed/JYQ0jumhjhY",
      "poster_path": "https://image.tmdb.org/t/p/w500//kvhrltQIRp1u84ao9uj52YPaWNY.jpg",
      "genre": "Horror",
      "original_language": "en"
    },
    {
      "id": "871799",
      "popularity": 789.755,
      "poster_path": "https://image.tmdb.org/t/p/w500//oUU6blOmIu155vfIgzML3ZSsDrB.jpg",
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//yKnjIWNIVECfMoKy1ayl68vX6qj.jpg",
      "adult": false,
      "title": "Pursuit",
      "trailer": "https://www.youtube.com/embed/7YEicjmt2KY",
      "plot": "Detective Breslin crosses paths with Calloway, a ruthless hacker desperate to find his wife, who has been kidnapped by a drug cartel. When Calloway escapes police custody, Breslin joins forces with a no-nonsense female cop to reclaim his prisoner. But is Calloway’s crime-boss father somehow involved in this explosive situation?",
      "genre": "Action",
      "release_date": "2022-02-18",
      "vote_average": 5.7
    },
    {
      "id": "876716",
      "poster_path": "https://image.tmdb.org/t/p/w500//1SyTnaY0wte69oKdqxQLvxPT3hs.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//qXctHIfK4LAgHH7qZiJJVCPclaY.jpg",
      "adult": false,
      "popularity": 255.196,
      "trailer": "https://www.youtube.com/embed/KJZS7oXX5SE",
      "genre": "Animation",
      "release_date": "2021-11-12",
      "original_language": "en",
      "vote_average": 7.5,
      "title": "Ciao Alberto",
      "plot": "With his best friend Luca away at school, Alberto is enjoying his new life in Portorosso working alongside Massimo – the imposing, tattooed, one-armed fisherman of few words – who's quite possibly the coolest human in the entire world as far as Alberto is concerned. He wants more than anything to impress his mentor, but it's easier said than done."
    },
    {
      "id": "890656",
      "popularity": 872.296,
      "trailer": "https://www.youtube.com/embed/vC_n_L1KGbo",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//wMUPT99gw6IB9OVvC46rF8wHIRt.jpg",
      "adult": false,
      "plot": "A revenge mission becomes a fight to save the world from an ancient threat when superpowered assassin Kai tracks a killer to Bangkok.",
      "title": "Fistful of Vengeance",
      "original_language": "en",
      "vote_average": 5.4,
      "release_date": "2022-02-17",
      "poster_path": "https://image.tmdb.org/t/p/w500//3cccEF9QZgV9bLWyupJO41HSrOV.jpg",
      "genre": "Action"
    },
    {
      "id": "892153",
      "vote_average": 7,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//q1NXVYTqSStNQsnKrCvtU6NPzEk.jpg",
      "genre": "Animation",
      "release_date": "2022-01-24",
      "title": "Tom and Jerry: Cowboy Up!",
      "original_language": "en",
      "adult": false,
      "poster_path": "https://image.tmdb.org/t/p/w500//muIaHotSaSUQr0KZCIJOYQEe7y2.jpg",
      "plot": "This time, the rivals team up to help a cowgirl and her brother save their homestead from a greedy land-grabber, and they’re going to need some help! Jerry’s three precocious nephews are all ready for action, and Tom is rounding up a posse of prairie dogs. But can a ragtag band of varmints defeat a deceitful desperado determined to deceive a damsel in distress? No matter what happens with Tom and Jerry in the saddle, it’ll be a rootin’ tootin’ good time!",
      "trailer": "https://www.youtube.com/embed/s5iqJVzhb3Q",
      "popularity": 573.891
    },
    {
      "id": "910596",
      "vote_average": 5.1,
      "trailer": "https://www.youtube.com/embed/b_3-oXMePZU",
      "original_language": "en",
      "title": "Run Gun",
      "popularity": 742.3,
      "poster_path": "https://image.tmdb.org/t/p/w500//4qlq5gPzWDZRfXJC9qgv9SfTThr.jpg",
      "adult": false,
      "plot": "After leaving a life of crime and violence, Ray is a reformed good guy, enjoying a quiet family life in the ‘burbs. But when his past is discovered, Ray is blackmailed into one last job to collect a mysterious package. After a deadly double-cross, he finds himself wounded and on the run from ruthless assassins who will stop at nothing to get what he has. Now, with the lives of his loved ones hanging in the balance and danger at every turn, Ray’s only hope is to draw upon his violent past to survive.",
      "genre": "Action",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//rf1hhEOEV4a7sP74Wlp9Ler4aUJ.jpg",
      "release_date": "2022-01-11"
    },
    {
      "id": "916740",
      "adult": false,
      "original_language": "en",
      "release_date": "2022-01-13",
      "title": "Brazen",
      "poster_path": "https://image.tmdb.org/t/p/w500//7e4n1GfC9iky9VQzH3cDQz9wYpO.jpg",
      "trailer": "https://www.youtube.com/embed/WJPSSL2lSjU",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//2Jp2RIwJ3Dt7vamkTt7llVJ7uY.jpg",
      "genre": "Thriller",
      "vote_average": 4.9,
      "popularity": 408.529,
      "plot": "Mystery writer Grace Miller has killer instincts when it comes to motive - and she'll need every bit of expertise to help solve her sister's murder."
    },
    {
      "id": "918832",
      "genre": "Animation",
      "poster_path": "https://image.tmdb.org/t/p/w500//xHvEiU3Ja1xiGt9oq2pu0huk5m3.jpg",
      "original_language": "en",
      "plot": "With help from a local fisherman, his niece and an adorable baby seal, George embarks on a quest in search of the long-lost shipwreck of legendary sea captain Trumpet Tooter.",
      "trailer": "https://www.youtube.com/embed/jRPmCZK24o0",
      "adult": false,
      "vote_average": 2.5,
      "release_date": "2021-09-30",
      "title": "Curious George: Cape Ahoy",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//kjJHSyhSIVRDw9KyGGxRYZZvYkI.jpg",
      "popularity": 324.668
    },
    {
      "id": "926899",
      "title": "The House",
      "plot": "Across different eras, a poor family, an anxious developer and a fed-up landlady become tied to the same mysterious house in this animated dark comedy.",
      "vote_average": 7.1,
      "adult": false,
      "genre": "Animation",
      "original_language": "en",
      "popularity": 523.491,
      "trailer": "https://www.youtube.com/embed/wqbZlAEUb5w",
      "release_date": "2022-01-14",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//hk4PwhKhT7q7jp1lvA8aiYqDluy.jpg",
      "poster_path": "https://image.tmdb.org/t/p/w500//iZjMFSKCrleKolC1gYcz5Rs8bk1.jpg"
    },
    {
      "id": "928381",
      "trailer": "https://www.youtube.com/embed/L8tCoWmooRE",
      "adult": false,
      "backdrop_path": "https://image.tmdb.org/t/p/w500//7CamWBejQ9JQOO5vAghZfrFpMXY.jpg",
      "popularity": 1157.525,
      "vote_average": 5.8,
      "poster_path": "https://image.tmdb.org/t/p/w500//9MP21x0OPv0R72obd63tMHssmGt.jpg",
      "original_language": "fr",
      "release_date": "2022-02-25",
      "plot": "After going to extremes to cover up an accident, a corrupt cop's life spirals out of control when he starts receiving threats from a mysterious witness.",
      "genre": "Action",
      "title": "Restless"
    },
    {
      "id": "928999",
      "genre": "Western",
      "original_language": "en",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//i5dUmY2xRzgkmjHJYKNj8kPX1Xx.jpg",
      "vote_average": 6,
      "plot": "After Kansas Red rescues young Billy from a card-game shootout, the boy asks Red for help protecting his family from the outlaw Thorn, who’s just kidnapped Billy’s mother, Carol. As Red and Billy ride off to rescue Carol, they run into beautiful, tough-as-nails Leslie, who’s managed to escape Thorn’s men. The three race to stop Thorn’s wedding to Carol with guns a-blazing - but does she want to be rescued?",
      "adult": false,
      "release_date": "2022-02-25",
      "trailer": "https://www.youtube.com/embed/AAwn9GqBiSY",
      "poster_path": "https://image.tmdb.org/t/p/w500//7pYYGm1dWZGkbJuhcuaHD6nE6k7.jpg",
      "title": "Desperate Riders",
      "popularity": 1117.963
    },
    {
      "id": "939336",
      "adult": false,
      "genre": "Animation",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//abnNjK3COZHZ4JQmzRbWhiWLum3.jpg",
      "plot": "The wonder of the winter season takes Mickey Mouse and his friends on a journey through three magical stories.",
      "original_language": "en",
      "vote_average": 6,
      "popularity": 254.541,
      "release_date": "2022-02-18",
      "title": "The Wonderful Winter of Mickey Mouse",
      "trailer": "https://www.youtube.com/embed/xHU5Fnzxcm4",
      "poster_path": "https://image.tmdb.org/t/p/w500//3dspgMFx64kA8BqkGZQK6Hk1sCV.jpg"
    },
    {
      "id": "944664",
      "popularity": 324.424,
      "original_language": "es",
      "genre": "Comedy",
      "title": "Without Saying Goodbye",
      "poster_path": "https://image.tmdb.org/t/p/w500//11SOeFmUEHahuyMOxxT1wdJ3iJs.jpg",
      "backdrop_path": "https://image.tmdb.org/t/p/w500//pIlIXdRiMzWMnjcPMyV5IBEvMwC.jpg",
      "vote_average": 6.9,
      "plot": "The opposite lives of a workaholic architect and a fiery artist are upended when their chance encounter in breathtaking Peru shifts their views on life.",
      "adult": false,
      "trailer": "https://www.youtube.com/embed/P6xDEDscFko",
      "release_date": "2022-03-18"
    }
  ]